apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{ values.name }}
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: ${{ values.name }}
    spec:
      containers:
      - image: nginx
        name: ${{ values.name }}
        resources: {}