---
name: Yaml Lint
on: [push]
jobs:
  CheckManifestsWithLinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone Repository
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Install Linter
        run: pip install --user yamllint

      - name: Lint YAML Files
        run: yamllint ${{ values.name }}/base/*.yaml
