---
name: Yaml Lint
on: [push]
jobs:
  CheckManifestsWithLinter:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
      - uses: actions/checkout@v3

      - name: Clone Repository
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Install Linter
        run: pip install --user yamllint

      - name: Lint YAML Files
        run: yamllint ${{ values.name }}/base/*.yaml
